//! `vendor/bin/` — the executables a package publishes.
//!
//! A package declares `"bin": ["phpunit"]`, and Composer puts a launcher at
//! `vendor/bin/phpunit`. That launcher is not a symlink: it is a PHP proxy that
//! sets two globals the target script relies on —
//!
//!     $GLOBALS['_composer_bin_dir']        where the launcher lives
//!     $GLOBALS['_composer_autoload_path']  which autoloader to use
//!
//! A symlink cannot do that, and a tool invoked through one resolves `__DIR__`
//! to the wrong place and loads the wrong autoloader (or none).
//!
//! Composer's generated proxy also carries a ~100-line stream-wrapper shim for
//! PHP < 8, whose entire job is stripping a shebang that PHP 8 handles by
//! itself. This platform requires PHP 8.4, so that branch is unreachable here
//! and is deliberately not reproduced — the proxy emitted below is the PHP 8
//! path of Composer's, and nothing else.

const std = @import("std");
const util = @import("util.zig");

const Io = std.Io;
const Dir = std.Io.Dir;

/// Create `vendor/bin/<name>` for one declared binary.
///
/// `package_rel` is the package directory relative to `vendor/`
/// (`phpunit/phpunit`); `bin_rel` is the script inside it (`phpunit`).
pub fn install(
    allocator: std.mem.Allocator,
    io: Io,
    vendor_dir: []const u8,
    package_rel: []const u8,
    bin_rel: []const u8,
) !void {
    const bin_dir = try std.fs.path.join(allocator, &.{ vendor_dir, "bin" });
    try Dir.cwd().createDirPath(io, bin_dir);

    const name = std.fs.path.basename(bin_rel);
    const target = try std.fmt.allocPrint(allocator, "{s}/{s}", .{ package_rel, std.mem.trim(u8, bin_rel, "/") });
    const path = try std.fs.path.join(allocator, &.{ bin_dir, name });

    try util.writeFileAtomic(io, path, try proxy(allocator, name, target));
    util.chmodExec(io, path);
}

/// The launcher script.
fn proxy(allocator: std.mem.Allocator, name: []const u8, target: []const u8) ![]const u8 {
    var out: std.ArrayList(u8) = .empty;

    try out.appendSlice(allocator,
        \\#!/usr/bin/env php
        \\<?php
        \\
        \\/**
        \\ * Proxy PHP file generated by `hkm ppkg install`
        \\ *
        \\ * Sets the globals a Composer-installed binary expects, then includes the
        \\ * real script. Not a symlink: a symlink resolves __DIR__ to the target's
        \\ * own directory, so the tool would look for its autoloader in the wrong
        \\ * place.
        \\ */
        \\
        \\namespace Composer;
        \\
        \\$GLOBALS['_composer_bin_dir'] = __DIR__;
        \\$GLOBALS['_composer_autoload_path'] = __DIR__ . '/../autoload.php';
        \\
    );

    // PHPUnit reads this global to keep its own launcher out of the list of
    // files re-included in an isolated child process. Composer special-cases it
    // for the same reason; without it, process-isolation tests re-enter the
    // proxy and fail in a way that has nothing to do with the test.
    if (std.mem.eql(u8, name, "phpunit")) {
        try out.appendSlice(allocator, "$GLOBALS['__PHPUNIT_ISOLATION_EXCLUDE_LIST'] = $GLOBALS['__PHPUNIT_ISOLATION_BLACKLIST'] = array(realpath(__DIR__ . '/../");
        try out.appendSlice(allocator, target);
        try out.appendSlice(allocator, "'));\n");
    }

    try out.appendSlice(allocator, "\nreturn include __DIR__ . '/../");
    try out.appendSlice(allocator, target);
    try out.appendSlice(allocator, "';\n");

    return out.toOwnedSlice(allocator);
}

// ── tests ─────────────────────────────────────────────────────────────────────

const testing = std.testing;

test "the proxy sets the globals a composer binary expects" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();

    const php = try proxy(arena.allocator(), "jsonlint", "seld/jsonlint/bin/jsonlint");

    try testing.expect(std.mem.startsWith(u8, php, "#!/usr/bin/env php\n<?php"));
    try testing.expect(std.mem.indexOf(u8, php, "$GLOBALS['_composer_bin_dir'] = __DIR__;") != null);
    try testing.expect(std.mem.indexOf(u8, php, "$GLOBALS['_composer_autoload_path'] = __DIR__ . '/../autoload.php';") != null);
    try testing.expect(std.mem.indexOf(u8, php, "return include __DIR__ . '/../seld/jsonlint/bin/jsonlint';") != null);
}

test "only phpunit gets the isolation exclude list" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();

    const unit = try proxy(a, "phpunit", "phpunit/phpunit/phpunit");
    try testing.expect(std.mem.indexOf(u8, unit, "__PHPUNIT_ISOLATION_EXCLUDE_LIST") != null);

    const other = try proxy(a, "php-parse", "nikic/php-parser/bin/php-parse");
    try testing.expect(std.mem.indexOf(u8, other, "__PHPUNIT_ISOLATION") == null);
}

test "a nested bin path keeps its directories but is named by its basename" {
    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();

    // symfony/var-dumper declares "Resources/bin/var-dump-server": the launcher
    // is `vendor/bin/var-dump-server`, pointing at the full inner path.
    const php = try proxy(arena.allocator(), "var-dump-server", "symfony/var-dumper/Resources/bin/var-dump-server");
    try testing.expect(std.mem.indexOf(u8, php, "'/../symfony/var-dumper/Resources/bin/var-dump-server';") != null);
    try testing.expectEqualStrings("var-dump-server", std.fs.path.basename("Resources/bin/var-dump-server"));
}
