//! Composer's loader — generated here, not borrowed from another tree.
//!
//! Five files in a vendor tree are neither package code nor generated data:
//!
//!     vendor/autoload.php                    the entry point everything requires
//!     vendor/composer/autoload_real.php      wires the loader to the data files
//!     vendor/composer/ClassLoader.php        the PSR-0/4 loader
//!     vendor/composer/InstalledVersions.php  the runtime package registry
//!     vendor/composer/LICENSE                the terms the two above ship under
//!
//! The first two are GENERATED, from the same templates `AutoloadGenerator`
//! interpolates — every conditional included, so a project with no
//! `autoload.files`, no platform check and no include paths gets exactly the
//! file Composer writes for it and not a superset with dead branches in it.
//!
//! The last three are Composer's own MIT-licensed source, embedded verbatim
//! from Composer {composer_source_version} along with its licence text.
//!
//! ## Why this changed
//!
//! These files used to be COPIED from a donor vendor tree, on the reasoning
//! that carrying someone else's code is a maintainer's decision rather than a
//! build tool's. The reasoning was sound and the consequence was not: on a
//! machine with no donor — a fresh checkout, a CI container, anyone who does
//! not already have Composer — an install placed every package correctly and
//! then reported that it could not produce an entry point, and told the
//! operator to run `composer install` once. A package manager whose failure
//! mode is "install the tool I replace" is bootstrapped by that tool, not a
//! substitute for it.
//!
//! Embedding is what closes that, and it costs the two things a copy was
//! avoiding, both of which are now handled here rather than deferred:
//!
//!   * the licence travels with the code — `res/LICENSE` is embedded and
//!     written beside it, which is what the MIT terms require and what
//!     Composer itself does with the same two files;
//!   * the copies go stale when Composer changes them. `composer_source_version`
//!     records what they were taken from, and `diagnose` reports it, so the
//!     drift is visible instead of silent.
//!
//! Generating the two suffix-bearing files also removes a whole class of bug
//! that copying created: a donor's `autoload_real.php` describes the donor's
//! project, so it had to be edited afterwards to add or remove the `$files`
//! block and the platform-check line to match the project it landed in. Those
//! edits are gone — the file is written correct the first time.

const std = @import("std");
const util = @import("util.zig");
const prompt = @import("report.zig");

const Io = std.Io;
const Dir = std.Io.Dir;

/// The Composer release `res/ClassLoader.php` and `res/InstalledVersions.php`
/// were taken from. Reported by `diagnose`, so a tree generated by an old
/// build of this tool can be told apart from one Composer wrote.
pub const composer_source_version = "2.10.3";

/// Composer's own MIT source, embedded rather than copied off the machine.
const class_loader_php = @embedFile("res/ClassLoader.php");
const installed_versions_php = @embedFile("res/InstalledVersions.php");
const license_txt = @embedFile("res/LICENSE");

/// Paths relative to a vendor directory. Used by `hasAll` and by `diagnose`.
pub const files = [_][]const u8{
    "autoload.php",
    "composer/autoload_real.php",
    "composer/ClassLoader.php",
    "composer/InstalledVersions.php",
    "composer/LICENSE",
};

pub const Status = enum {
    /// Written, or already byte-identical to what would have been written.
    generated,
    /// The vendor directory could not be written to.
    failed,
};

/// Everything `autoload_real.php` branches on.
///
/// Each field maps to one conditional block in `AutoloadGenerator::
/// getAutoloadRealFile`, and the defaults are Composer's defaults — so a
/// caller that fills in only `suffix` gets the file Composer generates for an
/// ordinary project.
pub const Loader = struct {
    /// The `ComposerAutoloaderInit<suffix>` / `ComposerStaticInit<suffix>` tag.
    /// MUST be the same value `autoload_static.php` was rendered with.
    suffix: []const u8,
    /// Emit `require __DIR__ . '/platform_check.php';` — only when a
    /// platform_check.php was actually written.
    check_platform: bool = true,
    /// Emit the `$filesToLoad` block — only when `autoload_files.php` exists.
    has_files: bool = false,
    /// Emit the `include_paths.php` block — only when that file exists.
    has_include_paths: bool = false,
    /// `config.classmap-authoritative` — never look at the filesystem.
    classmap_authoritative: bool = false,
    /// `config.apcu-autoloader` — the prefix to cache lookups under, already
    /// resolved (config value, or a random one the caller generated).
    apcu_prefix: ?[]const u8 = null,
    /// `config.use-include-path` — also consult PHP's include_path.
    use_include_path: bool = false,
    /// `config.prepend-autoloader` — register ahead of other autoloaders.
    prepend: bool = true,
};

/// Write the five loader files into `vendor_dir`.
///
/// Composer's `filePutContentsIfModified` semantics: a file whose content is
/// already what would be written is left alone, mtime included. That matters
/// for opcache and for build systems that stat the tree.
pub fn generate(
    allocator: std.mem.Allocator,
    io: Io,
    vendor_dir: []const u8,
    loader: Loader,
) Status {
    const composer_dir = std.fs.path.join(allocator, &.{ vendor_dir, "composer" }) catch return .failed;
    Dir.cwd().createDirPath(io, composer_dir) catch return .failed;

    const entry = autoloadFile(allocator, loader.suffix) catch return .failed;
    const real = autoloadRealFile(allocator, loader) catch return .failed;

    put(allocator, io, vendor_dir, "autoload.php", entry) catch return .failed;
    put(allocator, io, composer_dir, "autoload_real.php", real) catch return .failed;
    put(allocator, io, composer_dir, "ClassLoader.php", class_loader_php) catch return .failed;
    put(allocator, io, composer_dir, "InstalledVersions.php", installed_versions_php) catch return .failed;
    put(allocator, io, composer_dir, "LICENSE", license_txt) catch return .failed;

    return .generated;
}

fn put(allocator: std.mem.Allocator, io: Io, dir: []const u8, name: []const u8, body: []const u8) !void {
    const path = try std.fs.path.join(allocator, &.{ dir, name });
    _ = try util.writeFileIfModified(allocator, io, path, body);
}

// ── the two generated files ───────────────────────────────────────────────────

/// `vendor/autoload.php`.
///
/// `AutoloadGenerator` computes the path to `autoload_real.php` with
/// `findShortestPathCode`, but both ends of that calculation are inside the
/// vendor directory — `<vendor>/autoload.php` and `<vendor>/composer` — so it
/// yields `__DIR__ . '/composer'` for every layout, `config.vendor-dir`
/// included. The literal below is that result, not an assumption about where
/// the vendor directory is.
pub fn autoloadFile(allocator: std.mem.Allocator, suffix: []const u8) ![]const u8 {
    return std.fmt.allocPrint(allocator,
        \\<?php
        \\
        \\// autoload.php @generated by Composer
        \\
        \\if (PHP_VERSION_ID < 50600) {{
        \\    if (!headers_sent()) {{
        \\        header('HTTP/1.1 500 Internal Server Error');
        \\    }}
        \\    $err = 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.'.PHP_EOL;
        \\    if (!ini_get('display_errors')) {{
        \\        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {{
        \\            fwrite(STDERR, $err);
        \\        }} elseif (!headers_sent()) {{
        \\            echo $err;
        \\        }}
        \\    }}
        \\    throw new RuntimeException($err);
        \\}}
        \\
        \\require_once __DIR__ . '/composer/autoload_real.php';
        \\
        \\return ComposerAutoloaderInit{s}::getLoader();
        \\
    , .{suffix});
}

/// `vendor/composer/autoload_real.php`.
///
/// Assembled block by block in `AutoloadGenerator::getAutoloadRealFile`'s
/// order. The order is not cosmetic — `setClassMapAuthoritative` before
/// `register`, and the files loop after it, are what the loader's own
/// behaviour depends on.
pub fn autoloadRealFile(allocator: std.mem.Allocator, l: Loader) ![]const u8 {
    var out: std.ArrayList(u8) = .empty;
    const s = l.suffix;
    const prepend = if (l.prepend) "true" else "false";

    try out.print(allocator,
        \\<?php
        \\
        \\// autoload_real.php @generated by Composer
        \\
        \\class ComposerAutoloaderInit{s}
        \\{{
        \\    private static $loader;
        \\
        \\    public static function loadClassLoader($class)
        \\    {{
        \\        if ('Composer\Autoload\ClassLoader' === $class) {{
        \\            require __DIR__ . '/ClassLoader.php';
        \\        }}
        \\    }}
        \\
        \\    /**
        \\     * @return \Composer\Autoload\ClassLoader
        \\     */
        \\    public static function getLoader()
        \\    {{
        \\        if (null !== self::$loader) {{
        \\            return self::$loader;
        \\        }}
        \\
        \\
    , .{s});

    if (l.check_platform) {
        try out.appendSlice(allocator,
            \\        require __DIR__ . '/platform_check.php';
            \\
            \\
        );
    }

    try out.print(allocator,
        \\        spl_autoload_register(array('ComposerAutoloaderInit{s}', 'loadClassLoader'), true, {s});
        \\        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        \\        spl_autoload_unregister(array('ComposerAutoloaderInit{s}', 'loadClassLoader'));
        \\
        \\
    , .{ s, prepend, s });

    if (l.has_include_paths) {
        try out.appendSlice(allocator,
            \\        $includePaths = require __DIR__ . '/include_paths.php';
            \\        $includePaths[] = get_include_path();
            \\        set_include_path(implode(PATH_SEPARATOR, $includePaths));
            \\
            \\
        );
    }

    try out.print(allocator,
        \\        require __DIR__ . '/autoload_static.php';
        \\        call_user_func(\Composer\Autoload\ComposerStaticInit{s}::getInitializer($loader));
        \\
        \\
    , .{s});

    if (l.classmap_authoritative) {
        try out.appendSlice(allocator, "        $loader->setClassMapAuthoritative(true);\n");
    }

    if (l.apcu_prefix) |p| {
        // `var_export($prefix, true)` — a PHP single-quoted string literal.
        try out.appendSlice(allocator, "        $loader->setApcuPrefix('");
        for (p) |c| {
            if (c == '\'' or c == '\\') try out.append(allocator, '\\');
            try out.append(allocator, c);
        }
        try out.appendSlice(allocator, "');\n");
    }

    if (l.use_include_path) {
        try out.appendSlice(allocator, "        $loader->setUseIncludePath(true);\n");
    }

    try out.print(allocator,
        \\        $loader->register({s});
        \\
        \\
    , .{prepend});

    if (l.has_files) {
        try out.print(allocator,
            \\        $filesToLoad = \Composer\Autoload\ComposerStaticInit{s}::$files;
            \\        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {{
            \\            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {{
            \\                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;
            \\
            \\                require $file;
            \\            }}
            \\        }}, null, null);
            \\        foreach ($filesToLoad as $fileIdentifier => $file) {{
            \\            $requireFile($fileIdentifier, $file);
            \\        }}
            \\
            \\
        , .{s});
    }

    try out.appendSlice(allocator,
        \\        return $loader;
        \\    }
        \\}
        \\
    );

    return out.toOwnedSlice(allocator);
}

/// Recover `ComposerAutoloaderInit<suffix>` from a file's text.
///
/// Composer's own rule for reusing an existing tree's suffix, and the reason
/// a regenerated autoloader does not orphan the static file already in
/// opcache under the previous name.
pub fn suffixIn(text: []const u8) ?[]const u8 {
    const marker = "ComposerAutoloaderInit";
    const at = std.mem.indexOf(u8, text, marker) orelse return null;
    const rest = text[at + marker.len ..];
    var end: usize = 0;
    while (end < rest.len and (std.ascii.isAlphanumeric(rest[end]) or rest[end] == '_')) : (end += 1) {}
    if (end == 0) return null;
    return rest[0..end];
}

/// Does this vendor directory have every runtime file?
///
/// Kept for `diagnose`, which reports on a tree it did not write.
pub fn hasAll(allocator: std.mem.Allocator, io: Io, vendor_dir: []const u8) bool {
    for (files) |rel| {
        const path = std.fs.path.join(allocator, &.{ vendor_dir, rel }) catch return false;
        if (!util.fileExists(io, path)) return false;
    }
    return true;
}

/// Is the ClassLoader in this tree the one this build embeds?
///
/// `diagnose` reports a mismatch as information, never as a fault: a tree
/// Composer wrote most recently is EXPECTED to differ, and rewriting it here
/// would be this tool picking a fight with the other one over a file they
/// both legitimately generate.
pub fn classLoaderMatches(allocator: std.mem.Allocator, io: Io, vendor_dir: []const u8) bool {
    const path = std.fs.path.join(allocator, &.{ vendor_dir, "composer/ClassLoader.php" }) catch return false;
    const body = Dir.cwd().readFileAlloc(io, path, allocator, .limited(4 * 1024 * 1024)) catch return false;
    return std.mem.eql(u8, body, class_loader_php);
}

/// Report a loader that could not be written. Nothing else in the tree is
/// usable without it, so this is stated rather than folded into a count.
pub fn reportFailure() void {
    prompt.warn("vendor/ has no autoload.php: the loader could not be written. Check the directory is writable.");
}

test "autoload.php names the suffixed initialiser" {
    const a = std.testing.allocator;
    const out = try autoloadFile(a, "deadbeef");
    defer a.free(out);

    try std.testing.expect(std.mem.endsWith(u8, out, "return ComposerAutoloaderInitdeadbeef::getLoader();\n"));
    try std.testing.expect(std.mem.indexOf(u8, out, "require_once __DIR__ . '/composer/autoload_real.php';") != null);
    // The round trip Composer relies on to reuse a suffix.
    try std.testing.expectEqualStrings("deadbeef", suffixIn(out).?);
}

test "autoload_real.php: a plain project has no files block and no include paths" {
    const a = std.testing.allocator;
    const out = try autoloadRealFile(a, .{ .suffix = "abc123" });
    defer a.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, "$filesToLoad") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "include_paths.php") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "setClassMapAuthoritative") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "setApcuPrefix") == null);
    // Present by default: Composer emits the check unless it wrote no file.
    try std.testing.expect(std.mem.indexOf(u8, out, "require __DIR__ . '/platform_check.php';") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "$loader->register(true);") != null);
    try std.testing.expect(std.mem.endsWith(u8, out, "        return $loader;\n    }\n}\n"));
}

test "autoload_real.php: every conditional block appears where Composer puts it" {
    const a = std.testing.allocator;
    const out = try autoloadRealFile(a, .{
        .suffix = "abc123",
        .check_platform = false,
        .has_files = true,
        .has_include_paths = true,
        .classmap_authoritative = true,
        .apcu_prefix = "beef",
        .use_include_path = true,
        .prepend = false,
    });
    defer a.free(out);

    try std.testing.expect(std.mem.indexOf(u8, out, "platform_check.php") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "$loader->register(false);") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "spl_autoload_register(array('ComposerAutoloaderInitabc123', 'loadClassLoader'), true, false);") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "$loader->setApcuPrefix('beef');") != null);

    // Order is behaviour: authoritative and apcu are set on the loader BEFORE
    // it registers, and the files load AFTER — a files entry that instantiates
    // a class needs the loader already live.
    const authoritative = std.mem.indexOf(u8, out, "setClassMapAuthoritative").?;
    const apcu = std.mem.indexOf(u8, out, "setApcuPrefix").?;
    const use_include = std.mem.indexOf(u8, out, "setUseIncludePath").?;
    const register = std.mem.indexOf(u8, out, "$loader->register(").?;
    const files_block = std.mem.indexOf(u8, out, "$filesToLoad").?;
    const include_paths = std.mem.indexOf(u8, out, "include_paths.php").?;
    const static_init = std.mem.indexOf(u8, out, "autoload_static.php").?;

    try std.testing.expect(include_paths < static_init);
    try std.testing.expect(static_init < authoritative);
    try std.testing.expect(authoritative < apcu);
    try std.testing.expect(apcu < use_include);
    try std.testing.expect(use_include < register);
    try std.testing.expect(register < files_block);
}

test "apcu prefix is emitted as a PHP string literal, quotes escaped" {
    const a = std.testing.allocator;
    const out = try autoloadRealFile(a, .{ .suffix = "x", .apcu_prefix = "it's\\here" });
    defer a.free(out);

    // A prefix reaches this from config, which is a file anyone can edit — an
    // unescaped quote there would be a syntax error in every request.
    try std.testing.expect(std.mem.indexOf(u8, out, "setApcuPrefix('it\\'s\\\\here');") != null);
}
